# Generated by Django 2.2.1 on 2019-05-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('first_nam', models.CharField(max_length=30)),
                ('Sex', models.CharField(max_length=1)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
    ]
