# Generated by Django 2.2.1 on 2019-05-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
