# Generated by Django 2.2.1 on 2019-11-20 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='rendez_vous',
            new_name='date_inscription_command',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='sex',
            new_name='type_client',
        ),
        migrations.AddField(
            model_name='command',
            name='commentaire',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='rdv',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 17, 55, 34, 231229, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
