# Generated by Django 2.2.1 on 2019-06-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0003_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('domicile', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
