# Generated by Django 2.2.1 on 2019-06-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0004_auto_20190608_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
