# Generated by Django 2.2.1 on 2019-06-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0007_auto_20190614_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=1)),
                ('contact', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
