# Generated by Django 2.2.1 on 2019-06-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0008_auto_20190614_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='prix',
            field=models.CharField(default='20000', max_length=20),
            preserve_default=False,
        ),
    ]
