# Generated by Django 2.2.1 on 2019-06-24 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0010_auto_20190624_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='prix',
        ),
        migrations.AlterField(
            model_name='modeles',
            name='type_modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='k.Person'),
        ),
        migrations.CreateModel(
            name='Typeperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouvrier', models.CharField(blank=True, max_length=25, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='k.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k.Modeles')),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epaule', models.CharField(blank=True, max_length=2, null=True)),
                ('manche', models.CharField(blank=True, max_length=2, null=True)),
                ('taille', models.CharField(blank=True, max_length=2, null=True)),
                ('poitrine', models.CharField(blank=True, max_length=3, null=True)),
                ('long_boubou', models.CharField(blank=True, max_length=3, null=True)),
                ('long_patanlon', models.CharField(blank=True, max_length=3, null=True)),
                ('ceinture', models.CharField(blank=True, max_length=3, null=True)),
                ('cuisse', models.CharField(blank=True, max_length=3, null=True)),
                ('tour_manche', models.CharField(blank=True, max_length=2, null=True)),
                ('fesse', models.CharField(blank=True, max_length=3, null=True)),
                ('mesure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='k.Modeles')),
            ],
        ),
    ]
