# Generated by Django 2.2.1 on 2019-06-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0011_auto_20190624_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='mesure',
        ),
        migrations.AlterField(
            model_name='mesure',
            name='epaule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='k.Modeles'),
        ),
        migrations.AlterField(
            model_name='modeles',
            name='nombre',
            field=models.IntegerField(default=0),
        ),
    ]
