# Generated by Django 2.2.1 on 2019-06-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0012_auto_20190625_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='mesure_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='k.Modeles'),
        ),
        migrations.AddField(
            model_name='payement',
            name='payement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='k.Modeles'),
        ),
        migrations.AddField(
            model_name='typeperson',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='typeperson',
            name='quality_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='k.Person'),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='epaule',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='payement',
            name='prix_modele',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='client',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
