# Generated by Django 2.2.1 on 2019-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k', '0013_auto_20190625_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeles',
            name='type_modele',
        ),
        migrations.RemoveField(
            model_name='payement',
            name='payement',
        ),
        migrations.RemoveField(
            model_name='typeperson',
            name='quality_person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='person',
            name='genre',
        ),
        migrations.AddField(
            model_name='person',
            name='modele',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='prix',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='Mesure',
        ),
        migrations.DeleteModel(
            name='Modeles',
        ),
        migrations.DeleteModel(
            name='Payement',
        ),
        migrations.DeleteModel(
            name='Typeperson',
        ),
    ]
